language: java
script:
  - ./gradlew build --scan -s

matrix:
  include:
    - jdk: openjdk11

    # osx build
    - os: osx
      # default osx image only has java 10, osx 9.3 has jdk8 pre-installed
      osx_image: xcode9.3
